[package]
name = "Fe2O3"
version = "0.1.0"
authors = ["Aaditya Rautela <aadityarautela@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.15.3"
rodio = "0.11.0"
rand = "0.7"